const actionTypes = {
  SELECT_DASHBOARD_PAGE: 'SELECT_DASHBOARD_PAGE',
  AUTHORIZE_ADMIN: 'AUTHORIZE_ADMIN',
  SET_ADMIN_DATA: 'SET_ADMIN_DATA',
  DOWNLOAD_DATA_FILE: 'DOWNLOAD_DATA_FILE',
};

export default actionTypes;
