const actionTypes = {
  SELECT_DASHBOARD_PAGE: 'SELECT_DASHBOARD_PAGE',
  AUTHORIZE_ADMIN: 'AUTHORIZE_ADMIN',
  SET_ADMIN_DATA: 'SET_ADMIN_DATA',
  SET_ADMIN_FOOD_ITEMS: 'SET_ADMIN_FOOD_ITEMS',
  DOWNLOAD_DATA_FILE: 'DOWNLOAD_DATA_FILE',
  SET_PICKUP_TIME_START: 'SET_PICKUP_TIME_START',
  SET_PICKUP_TIME_END: 'SET_PICKUP_TIME_END',
  SET_VOTE_TIME_BEG: 'SET_VOTE_TIME_BEG',
  SET_VOTE_TIME_END: 'SET_VOTE_TIME_END',
  // SET_FOOD_ITEMS: 'SET_FOOD_ITEMS',
  SET_PREV_STEP: 'SET_PREV_STEP',
  SET_NEXT_STEP: 'SET_NEXT_STEP',
  SUBMIT_NEW_BULK_BUY: 'SUBMIT_NEW_BULK_BUY',
};

export default actionTypes;
