const actionTypes = {
  SELECT_DASHBOARD_PAGE: 'SELECT_DASHBOARD_PAGE',
  AUTHORIZE_ADMIN: 'AUTHORIZE_ADMIN',
  SET_ADMIN_DATA: 'SET_ADMIN_DATA',
  DOWNLOAD_SUMMARY: 'DOWNLOAD_SUMMARY',
  DOWNLOAD_FOOD_BALLOTS: 'DOWNLOAD_FOOD_BALLOTS',
  DOWNLOAD_PARTICIPANT_DATA: 'DOWNLOAD_PARTICIPANT_DATA',
};

export default actionTypes;
