const actionTypes = {
  SET_DATE: 'SET_DATE',
  SET_VOTE: 'SET_VOTE',
  SET_REMAINING_CALENDAR: 'SET_REMAINING_CALENDAR',
  SET_PROVIDER: 'SET_PROVIDER',
  SET_LOCATION: 'SET_LOCATION',
  SET_CURRENT_FUTURE_DROPOFFS: 'SET_CURRENT_FUTURE_DROPOFFS',
  TOGGLE_HOME_MAP: 'TOGGLE_HOME_MAP',
  LOGOUT: 'LOGOUT',
  SET_PREV_STEP: 'SET_PREV_STEP',
  SET_NEXT_STEP: 'SET_NEXT_STEP',
};

export default actionTypes;
