const actionTypes = {
  SET_USER_AUTHENTICATED: 'SET_USER_AUTHENTICATED',
  SET_USER_AUTHORIZED: 'SET_USER_AUTHORIZED',
  SET_BALLOTS_AND_VOTES: 'SET_BALLOTS_AND_VOTES',
  SET_FIREBASE_ACCESS_TOKEN: 'SET_FIREBASE_ACCESS_TOKEN',
  SET_LOADING: 'SET_LOADING',
  SET_ROUTE_TO_REGISTER_FORM: 'SET_ROUTE_TO_REGISTER_FORM',
  SET_USER_WANTS_EMAIL_SIGNUP: 'SET_USER_WANTS_EMAIL_SIGNUP',
  SET_FACEBOOK_DATA: 'SET_FACEBOOK_DATA',
  SET_USER_TRANSACTION_HISTORY: 'SET_USER_TRANSACTION_HISTORY',
  SET_AVAILABLE_DELIVERIES_LEFT: 'SET_AVAILABLE_DELIVERIES_LEFT',
  SET_DELIVERY_ELIGIBILITY_OBJ: 'SET_DELIVERY_ELIGIBILITY_OBJ',
  LOGOUT: 'LOGOUT',
};

export default actionTypes;
